name: CI (minimal)
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test --all
      - name: Run bins (smoke)
        run: |
          set -e
          if [ -d src/bin ] && ls src/bin/*.rs >/dev/null 2>&1; then
            for f in src/bin/*.rs; do
              b="$(basename "$f" .rs)"
              echo "==> cargo run --bin $b"
              cargo run --quiet --bin "$b"
            done
          else
            echo "No bins in src/bin"
          fi
